<?php 
# Code generated by sdkgen
# Generated on 2020-07-21 21:11:20.314667273 +0000 UTC using container gcr.io/repcore-prod/sdkgen:latest
# DO NOT EDIT!
namespace Vendasta\SalesOrders\V1\internal;

use Vendasta\SalesOrders\V1\Config;

class NotificationsGeneratedClient
{
    private $transport;
    
    /**
     * NotificationsGeneratedClient constructor.
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     */
    public function __construct(string $env, float $default_timeout = 10000)
    {
        $this->transport = $this->getTransportClient($env, $default_timeout);
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @param float $default_timeout
     * @return NotificationsClientInterface
     */
    private function getTransportClient(string $env, float $default_timeout = 10000): NotificationsClientInterface
    {
        $config = $this->getEnvConfig($env);

        if (class_exists('Grpc\ChannelCredentials', true)) {
            return new NotificationsGRPCClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        } else {
            return new NotificationsHTTPClient(
                $config['host'],
                $config['scope'],
                $config['secure'],
                $default_timeout
            );
        }
    }

    /**
     * @param string $env one of \Vendasta\Vax\Environment::<Env>
     * @return array
     */
    private function getEnvConfig(string $env): array {
        return Config::ENVIRONMENT_PARAMS[$env];
    }
    
    /**
     * @param \Salesorders\V1\SubscribeRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Subscribe(\Salesorders\V1\SubscribeRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->Subscribe($req, $options);
    }
    
    /**
     * @param \Salesorders\V1\UnsubscribeRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Google\Protobuf\GPBEmpty proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function Unsubscribe(\Salesorders\V1\UnsubscribeRequest $req, array $options = []): \Google\Protobuf\GPBEmpty
    {
        return $this->transport->Unsubscribe($req, $options);
    }
    
    /**
     * @param \Salesorders\V1\GetSubscribedLocationsRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Salesorders\V1\GetSubscribedLocationsResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetSubscribedLocations(\Salesorders\V1\GetSubscribedLocationsRequest $req, array $options = []): \Salesorders\V1\GetSubscribedLocationsResponse
    {
        return $this->transport->GetSubscribedLocations($req, $options);
    }
    
    /**
     * @param \Salesorders\V1\GetSubscribersRequest $req proto request message
     * @param array $options optional options, possible keys:
     *              \Vendasta\Vax\RequestOptions::*
     * @return \Salesorders\V1\GetSubscribersResponse proto response message
     * @throws \Vendasta\Vax\SDKException if this call encounters an error
     */
    public function GetSubscribers(\Salesorders\V1\GetSubscribersRequest $req, array $options = []): \Salesorders\V1\GetSubscribersResponse
    {
        return $this->transport->GetSubscribers($req, $options);
    }
    
}
